# Generated by Django 5.0.1 on 2024-02-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basic_info", "0003_alter_patient_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_prescription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
